database:
    - active: false,
    - connectionString: mongodb://localhost/bluerouter

routesWithoutDB:
            - param: v1
              url: http://jsonip.com
            - param: v2
              url: http://jsonip.com